### ISSUE TITLE
Zvážit přidání RF přepínače

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/ISM02#6]
Pro některé aplikace, kdy bude potřeba obousměrný přenos by možná bylo vhodné do modulu zahrnout přímo RF přepínač. 
Zřejmě stejný typ jako je použit v modulu [RFSWITCH](https://github.com/mlab-modules/RFSWITCH01).

RF přepínač byl původně během návrhu tohoto modulu vyhozen, neboť nebyl dostatečně rychle nalezen vhodný typ.  Aktuální typ z modulu RFSWITCH tento problém řeší. 
Je jen potřeba znovu nalézt katalogové zapojení podle kterého má být RF přepínač ovládán. 

Tato úprava ale není blokující pro výrobu další verze modulu, neboť stejné funkčnosti je možné dosáhnout externím připojením modulu [RFSWITCH01A](https://github.com/mlab-modules/RFSWITCH01).

**Comment by ChroustJan** [comment]
Jedná se o přepínač [PE4259](https://www.psemi.com/pdf/datasheets/pe4259ds.pdf)

**Comment by kaklik** [comment]
Ovládání přepínače je zřejmě potřeba v IO zapnout příkazem viz tato část datasheetu: 

![image](https://user-images.githubusercontent.com/1194177/112153340-71eb1180-8be3-11eb-9794-9daab88c9371.png)

**Comment by ChroustJan** [comment]
Přepínač byl aplikován do verze ISM02B.
